# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cmcarthur/Documents/Programming

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cmcarthur/Documents/Programming

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmcarthur/Documents/Programming/CMakeFiles /home/cmcarthur/Documents/Programming/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmcarthur/Documents/Programming/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clsocket-example

# Build rule for target.
clsocket-example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clsocket-example
.PHONY : clsocket-example

# fast build rule for target.
clsocket-example/fast:
	$(MAKE) -f CMakeFiles/clsocket-example.dir/build.make CMakeFiles/clsocket-example.dir/build
.PHONY : clsocket-example/fast

#=============================================================================
# Target rules for targets named clsocket

# Build rule for target.
clsocket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clsocket
.PHONY : clsocket

# fast build rule for target.
clsocket/fast:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/build
.PHONY : clsocket/fast

#=============================================================================
# Target rules for targets named querydaytime-example

# Build rule for target.
querydaytime-example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 querydaytime-example
.PHONY : querydaytime-example

# fast build rule for target.
querydaytime-example/fast:
	$(MAKE) -f CMakeFiles/querydaytime-example.dir/build.make CMakeFiles/querydaytime-example.dir/build
.PHONY : querydaytime-example/fast

#=============================================================================
# Target rules for targets named echoserver-example

# Build rule for target.
echoserver-example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echoserver-example
.PHONY : echoserver-example

# fast build rule for target.
echoserver-example/fast:
	$(MAKE) -f CMakeFiles/echoserver-example.dir/build.make CMakeFiles/echoserver-example.dir/build
.PHONY : echoserver-example/fast

examples/EchoServer.o: examples/EchoServer.cpp.o

.PHONY : examples/EchoServer.o

# target to build an object file
examples/EchoServer.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver-example.dir/build.make CMakeFiles/echoserver-example.dir/examples/EchoServer.cpp.o
.PHONY : examples/EchoServer.cpp.o

examples/EchoServer.i: examples/EchoServer.cpp.i

.PHONY : examples/EchoServer.i

# target to preprocess a source file
examples/EchoServer.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver-example.dir/build.make CMakeFiles/echoserver-example.dir/examples/EchoServer.cpp.i
.PHONY : examples/EchoServer.cpp.i

examples/EchoServer.s: examples/EchoServer.cpp.s

.PHONY : examples/EchoServer.s

# target to generate assembly for a file
examples/EchoServer.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver-example.dir/build.make CMakeFiles/echoserver-example.dir/examples/EchoServer.cpp.s
.PHONY : examples/EchoServer.cpp.s

examples/QueryDayTime.o: examples/QueryDayTime.cpp.o

.PHONY : examples/QueryDayTime.o

# target to build an object file
examples/QueryDayTime.cpp.o:
	$(MAKE) -f CMakeFiles/querydaytime-example.dir/build.make CMakeFiles/querydaytime-example.dir/examples/QueryDayTime.cpp.o
.PHONY : examples/QueryDayTime.cpp.o

examples/QueryDayTime.i: examples/QueryDayTime.cpp.i

.PHONY : examples/QueryDayTime.i

# target to preprocess a source file
examples/QueryDayTime.cpp.i:
	$(MAKE) -f CMakeFiles/querydaytime-example.dir/build.make CMakeFiles/querydaytime-example.dir/examples/QueryDayTime.cpp.i
.PHONY : examples/QueryDayTime.cpp.i

examples/QueryDayTime.s: examples/QueryDayTime.cpp.s

.PHONY : examples/QueryDayTime.s

# target to generate assembly for a file
examples/QueryDayTime.cpp.s:
	$(MAKE) -f CMakeFiles/querydaytime-example.dir/build.make CMakeFiles/querydaytime-example.dir/examples/QueryDayTime.cpp.s
.PHONY : examples/QueryDayTime.cpp.s

examples/RecvAsync.o: examples/RecvAsync.cpp.o

.PHONY : examples/RecvAsync.o

# target to build an object file
examples/RecvAsync.cpp.o:
	$(MAKE) -f CMakeFiles/clsocket-example.dir/build.make CMakeFiles/clsocket-example.dir/examples/RecvAsync.cpp.o
.PHONY : examples/RecvAsync.cpp.o

examples/RecvAsync.i: examples/RecvAsync.cpp.i

.PHONY : examples/RecvAsync.i

# target to preprocess a source file
examples/RecvAsync.cpp.i:
	$(MAKE) -f CMakeFiles/clsocket-example.dir/build.make CMakeFiles/clsocket-example.dir/examples/RecvAsync.cpp.i
.PHONY : examples/RecvAsync.cpp.i

examples/RecvAsync.s: examples/RecvAsync.cpp.s

.PHONY : examples/RecvAsync.s

# target to generate assembly for a file
examples/RecvAsync.cpp.s:
	$(MAKE) -f CMakeFiles/clsocket-example.dir/build.make CMakeFiles/clsocket-example.dir/examples/RecvAsync.cpp.s
.PHONY : examples/RecvAsync.cpp.s

src/ActiveSocket.o: src/ActiveSocket.cpp.o

.PHONY : src/ActiveSocket.o

# target to build an object file
src/ActiveSocket.cpp.o:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/ActiveSocket.cpp.o
.PHONY : src/ActiveSocket.cpp.o

src/ActiveSocket.i: src/ActiveSocket.cpp.i

.PHONY : src/ActiveSocket.i

# target to preprocess a source file
src/ActiveSocket.cpp.i:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/ActiveSocket.cpp.i
.PHONY : src/ActiveSocket.cpp.i

src/ActiveSocket.s: src/ActiveSocket.cpp.s

.PHONY : src/ActiveSocket.s

# target to generate assembly for a file
src/ActiveSocket.cpp.s:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/ActiveSocket.cpp.s
.PHONY : src/ActiveSocket.cpp.s

src/PassiveSocket.o: src/PassiveSocket.cpp.o

.PHONY : src/PassiveSocket.o

# target to build an object file
src/PassiveSocket.cpp.o:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/PassiveSocket.cpp.o
.PHONY : src/PassiveSocket.cpp.o

src/PassiveSocket.i: src/PassiveSocket.cpp.i

.PHONY : src/PassiveSocket.i

# target to preprocess a source file
src/PassiveSocket.cpp.i:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/PassiveSocket.cpp.i
.PHONY : src/PassiveSocket.cpp.i

src/PassiveSocket.s: src/PassiveSocket.cpp.s

.PHONY : src/PassiveSocket.s

# target to generate assembly for a file
src/PassiveSocket.cpp.s:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/PassiveSocket.cpp.s
.PHONY : src/PassiveSocket.cpp.s

src/SimpleSocket.o: src/SimpleSocket.cpp.o

.PHONY : src/SimpleSocket.o

# target to build an object file
src/SimpleSocket.cpp.o:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/SimpleSocket.cpp.o
.PHONY : src/SimpleSocket.cpp.o

src/SimpleSocket.i: src/SimpleSocket.cpp.i

.PHONY : src/SimpleSocket.i

# target to preprocess a source file
src/SimpleSocket.cpp.i:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/SimpleSocket.cpp.i
.PHONY : src/SimpleSocket.cpp.i

src/SimpleSocket.s: src/SimpleSocket.cpp.s

.PHONY : src/SimpleSocket.s

# target to generate assembly for a file
src/SimpleSocket.cpp.s:
	$(MAKE) -f CMakeFiles/clsocket.dir/build.make CMakeFiles/clsocket.dir/src/SimpleSocket.cpp.s
.PHONY : src/SimpleSocket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... clsocket-example"
	@echo "... clsocket"
	@echo "... querydaytime-example"
	@echo "... echoserver-example"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... examples/EchoServer.o"
	@echo "... examples/EchoServer.i"
	@echo "... examples/EchoServer.s"
	@echo "... examples/QueryDayTime.o"
	@echo "... examples/QueryDayTime.i"
	@echo "... examples/QueryDayTime.s"
	@echo "... examples/RecvAsync.o"
	@echo "... examples/RecvAsync.i"
	@echo "... examples/RecvAsync.s"
	@echo "... src/ActiveSocket.o"
	@echo "... src/ActiveSocket.i"
	@echo "... src/ActiveSocket.s"
	@echo "... src/PassiveSocket.o"
	@echo "... src/PassiveSocket.i"
	@echo "... src/PassiveSocket.s"
	@echo "... src/SimpleSocket.o"
	@echo "... src/SimpleSocket.i"
	@echo "... src/SimpleSocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

